- hosts: webserver
  become: true
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        update_cache: yes
    - name: Pull webapp image
      docker_image:
        name: mywebapp
        source: pull
    - name: Run webapp container
      docker_container:
        name: mywebapp
        image: mywebapp
        ports:
          - "3000:3000"
        restart_policy: always
