---
- name: Build and deploy web server
  hosts: all
  become: true
  vars:
    app_port: 80
    app_path: /var/www/my-web-server
  tasks:
    - name: Copy web files
      copy:
        src: index.html
        dest: "{{ app_path }}/index.html"
        mode: 0755
