---
- hosts: all
  become: true
  vars:
    docker_image_name: lstar974/hebergement
    docker_image_tag: latest

  tasks:
    - name: Démarrer le service Docker
      systemd:
        name: docker
        state: started

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}:{{ docker_image_tag }}"
        source: pull

    - name: Stopper le conteneur s'il est déjà en cours d'exécution
      docker_container:
        name: "{{ docker_image_name }}-container"
        state: stopped
        force_kill: yes
      register: stopped_container
      ignore_errors: yes

    - name: Supprimer le conteneur s'il existe déjà
      docker_container:
        name: "{{ docker_image_name }}-container"
        state: absent
      when: stopped_container is defined and stopped_container is succeeded

    - name: Démarrer le nouveau conteneur
      docker_container:
        name: "{{ docker_image_name }}-container"
        image: "{{ docker_image_name }}:{{ docker_image_tag }}"
        ports:
          - "80:80"
        state: started
